//
//  AnswerLibrary.swift
//  AnswerBook
//
//  Created by HellöM on 2020/3/11.
//  Copyright © 2020 HellöM. All rights reserved.
//

import Foundation

var answerList: [String] =
    ["聽取專家的意見", "採取一個大膽的態度", "千萬別在這上面押寶", "研究，然後享受它", "專注在你的家庭生活上吧",
     "你會發現你自己無法妥協", "當然", "它仍然無法預測", "最好等等看", "帶著好奇心去探索它", "絕對不", "對別人保密",
     "趁早做", "確定的事實", "可能會發生一些令人吃驚的事", "答案或許是以另一種語言形式來到你身邊", "它將會帶來好運",
     "懷疑它", "你將需要適當調整一下", "你將會發現你所需要知道的一切", "要有點耐心", "你將會很開心你這樣做了", "把它記錄下來",
     "這時候非常不順利", "改變你焦點", "千萬別陷入你的感情", "如果好就好；如果不好，馬上放棄", "如果你照它說的做",
     "用任何你能做到的方式去進行", "這時候不要要求太多", "避開第一個解決方案", "你說了算", "它會影響別人看你的眼光",
     "多多觀察，別輕舉妄動", "保持樂觀", "最好的答案往往都不是輕而易見的那個", "放輕鬆去看待", "這不是你所能控制的",
     "用心去感激", "別忽略細節", "警慎的處理", "好好去享受", "別再猶豫了", "毫無保留的把它說出來", "可以，但請小心行事",
     "它具有非常重要的意義", "重新思考輕重緩急", "為什麼不", "繼續往前", "現在是這個計畫的最佳時機", "去解決吧", "你無法忘懷",
     "別再等了", "尋找其他選擇", "該去兌現了", "隨著他人指引", "暫緩行事", "主動出擊", "接受它", "值得一試", "無法保證",
     "情況無法預期", "轉變得非常快速", "莫忘初衷", "盡心盡力", "還不夠", "你不得不接受", "它將會帶來不好的事情", "會是一場轟動",
     "會是一場災難", "不得不終止", "仔細聆聽", "你將會明白", "沒問題", "別知道的太多", "是一種浪費", "那將會是一種金錢的浪費",
     "隨它去吧", "不可避免", "就在你身邊", "全力以赴", "別去在意", "浪費時間", "一年後", "一年內", "你需要好好考慮",
     "假裝他已經是真的", "數到10，再問一次", "非同凡響", "過程是必須的", "發揮你的想像力", "等待...", "確保是對的，冷靜下來",
     "它一定會很好", "別人將會接受你的選擇", "去接受他人的選擇", "一笑置之", "當你做了，你將需要不斷彌補", "你將會後悔的", "無可厚非",
     "相信自己的直覺", "相信別人", "會比現在更好", "不會比現在更好", "可能在你老的時候", "去問問你媽", "去問問你爸", "去問問你朋友",
     "在評估一下", "一次就好", "可能會", "可能不會", "不行", "別傻了", "你的行動將會有改善的", "專注在現在的事情上", "換個想法",
     "你將會無法妥協", "相信專業", "無法預測", "活在當下", "享受它", "保持好奇心", "請保密",
     "別太相信任何人", "直得嘗試", "欣然接受", "適當的調適一下", "不會後悔", "照自己的想法去做", "放棄舊的方法",
     "接受新的方法", "別單獨", "別團體", "與人合作", "賭一把", "專注在現在的工作上", "風雨無阻", "別看得太近", "越近越好",
     "越遠越好", "最好不要", "防範小人", "相信它", "先將手邊的事情完成", "還不明朗", "必須努力", "可能該放棄了",
     "錯過這個機會，不知道還要等多久", "先休息一下", "早點定下來", "等待時機", "它將是不可取的", "別太緊張", "到一定的高度再說",
     "去取得更加清晰的視野", "直得冒險", "節省你的能量吧", "實際點", "他將會與你同行", "別太超過", "收斂一點", "現在的你可以",
     "現在的你還不行", "你將會為它付出代價", "會是有趣的", "可能不太有趣", "肯定的", "無論是什麼，都不用怕", "積極點", "慷慨點",
     "有失有得", "你可能必須要放棄其他的東西", "別擔心", "分享出去", "沒有意義", "有它的意義", "請做好準備", "你無法控制",
     "無論你怎麼做，都改變不了", "過程艱難，但是結果是有價值的", "它將會是一個麻煩", "你肯定需要支持", "相關問題將會接二連三",
     "需要去克服它", "會是好的發展", "不太建議", "它會是一個關鍵", "不要太固執", "需要有主見一點", "只許成功，不可失敗", "繼承下去",
     "已是事實", "你將不會失望", "可能會失敗", "可能會失去", "可能會得到", "不拘小節", "見機行事", "遵守規則", "如果你不抵抗",
     "它不值得努力", "明天再問一次", "不告訴你", "可能會成功"]

var answerEnList: [String] =
    ["Hear from experts.", "Take a bold attitude.", "Don't bet on this.", "Study and then enjoy it.",
     "Focus on your family life.", "You'll find yourself unable to compromise.", "Of course.",
     "It's still unpredictable.", "Better wait and see.", "Explore it with curiosity.", "Absolutely not.",
     "Keep it a secret to others.", "Do it early.", "The facts that are determined.",
     "Something surprising could happen.", "The answer may be to come to you in another language.",
     "It's going to bring good luck.", "Doubt it.", "You'll need to adjust it appropriately.",
     "You'll find everything you need to know.", "Be a little patient.", "You'll be glad you did.",
     "Write it down.", "It's a very rough time.", "Change your focus.", "Don't fall into your feelings.",
     "If it's good, if it's not good, give up right away.", "If you do what it says.",
     "Do it any way you can.", "Don't ask too much at this time.", "Avoid the first solution", "You're right.",
     "It affects how people look at you.", "Watch more, don't act rashly.", "Stay optimistic.",
     "The best answers are often not the ones that are light and easy to see.", "Take it easy to look at.",
     "It's not with in your control.", "To be grateful with your heart.", "Don't ignore the details.",
     "Caution's handling.", "Enjoy it.", "Don't hesitate.", "Say it without reservation.", "Yes, but be careful.",
     "It's very important.", "Rethinking priorities.", "Why not.", "Keep going.",
     "Now is the best time for this plan.", "Let's deal with it.", "You can't forget.",
     "Don't wait any longer.", "Find other options.", "It's time to cash in.", "Follow others' guidance.",
     "Suspend the act.", "Active attack.", "Accept it.", "Worth a try.", "Can not guarantee.",
     "The situation is not expected.", "Change very quickly.", "Never forget your original intention.",
     "Make all-out efforts.", "not enough yet.", "You can't say no.", "It's going to bring bad things.",
     "It's going to be a sensation.", "It would be a disaster.", "Had to terminate.", "Listen carefully.",
     "You will understand.", "No problem.", "I do not know too much.", "It is a waste.",
     "That would be a waste of money.", "Let it go.", "Unavoidable.", "On your side.", "Go to all lengths.",
     "Don't care.", "waste time.", "one year later.", "Within a year.", "You need to carefully consider.",
     "Pretending he is really.", "Count to 10, ask again.", "Extraordinary.", "Process is necessary.",
     "Use your imagination.", "wait...", "Make sure is right, calm down.", "It will be very good.",
     "Others will accept your choice.", "To accept the choices of others.", "laugh it off.",
     "When you do, you will need to make up for it.", "You will regret it.", "Nothing wrong.",
     "Trust your instincts.", "Trust others.", "It will be better than it is now.", "Not better than it is now.",
     "Maybe After you get older.", "Go ask your mother.", "Go ask your dad.", "Go ask your friends.",
     "Evaluation is also needed.", "Just once.", "Maybe.", "May not be.", "No way.", "Do not be silly.",
     "Your actions will have improved.", "Focus on the present.", "Another idea.",
     "You will not be able to compromise.", "Believe in the professional.", "unpredictable.",
     "Living in the moment.", "Enjoy it.", "Keep curious.", "Please secrecy.", "Do not trust anyone.", "Just try.",
     "Gladly accepted.", "Adjust properly.", "You will not regret.", "According to their own ideas to do.",
     "Abandon the old method.", "Accept the new method.", "Do not alone.", "Do not group.",
     "Cooperation with others.", "Bet once.", "Now focus on the work.", "Rain or shine.", "Do not look too close.",
     "The closer the better.", "The farther the better.", "better not.", "Prevention villain.", "Believe it.",
     "Finish what you have at hand.", "It's not clear yet.", "Must work hard.", "Maybe it's time to give up.",
     "Miss this opportunity, don't know how long to wait.", "Take a break.", "Settle down early.",
     "Waiting for an opportunity.", "It will not be desirable.", "Don't be too nervous.",
     "To a certain height to say.", "To get a clearer vision.", "Straight Adventure.", "Save your energy.",
     "The actual point.", "He will walk with you.", "Don't Overdone.", "Convergence point.", "Now you can.",
     "Now you is not enough.", "You will pay the price for it.", "It will be interesting.",
     "It may be less interesting.", "definitely.", "No matter what do not be afraid.", "Positive points.",
     "Generosity.", "There are gains and losses.", "You may have to give up other things.", "do not worry.",
     "Share it.", "Pointless.", "It has its significance.", "Please get ready.", "You can not control.",
     "No matter how you do, can't change.", "Difficult process, but the result is valuable.",
     "It will be a problem.", "You definitely need support.", "Related issues will be one after another.",
     "The need to overcome it.", "It would be a good development.", "Do not recommend.", "It will be a key.",
     "Do not be too stubborn.", "Need to be proactive.", "Only succeed, not fail.", "Inherit it.",
     "Has become a fact.", "You will not be disappointed.", "May fail.", "May be lost", "You may get.",
     "Not to stick at trifles.", "Act according to circumstances.", "Follow the rules.", "If you do not resist.",
     "It's not worth the effort.", "Tomorrow ask again.", "Not tell you.", "You may succeed."]
